### PR TITLE
Added custom colour

### LINKED ISSUE #4: Add Custom color for the  search component
Could not add custom color its just the default white (0xffffff)

### PR DESCRIPTION
**Pull request by kherldhussein**
Enable custom color

### CODE REVIEW

**Comment by Imgkl** [comment]
@kherld-hussein Could you please add a preview of the search bar with custom color?

**Comment by Imgkl** [comment]
Also, Since I've migrated to the null safety, your PR has some conflicts, can you resolve them please.

**Comment by kherldhussein** [comment]
[Example](https://github.com/Imgkl/anim_search_bar/pull/5#issuecomment-792700914)

> @kherld-hussein Could you please add a preview of the search bar with custom color?

Was using the package and had to change to dark theme on my app so the search bar could not offer me to customize the way I'd like.
Had the same white on light and dark theme ...Hope you'll understand

**Comment by kherldhussein** [comment]
> Also, Since I've migrated to the null safety, your PR has some conflicts, can you resolve them please.

Resolving that

**Comment by Imgkl** [comment]
Hey @kherld-hussein 😊,

I tested your code, There are three minor issues though. 

 - You are checking if the color is defined by the user, if not use Colors.white, by using this condition 

`color: Colors.white ?? widget.color`

but instead, it should be like this

` color: widget.color ?? Colors.white,`.

 - Also, You have added duplicated initialization of the `onSuffixTap`, please remove one from either line 42 or 46.

- You missed adding the color in line 129.

Other than that, this PR looks good to be merged.

**Review by Imgkl — APPROVED** [review]

**Pull request merged**
